/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Videos */
        get: operations["list_videos_api_videos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/videos/{video_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review */
        get: operations["get_review_api_videos__video_id__review_get"];
        put?: never;
        /** Save Review */
        post: operations["save_review_api_videos__video_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/videos/{video_id}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render Review */
        post: operations["render_review_api_videos__video_id__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{video_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Media */
        get: operations["media_media__video_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * EditAction
         * @enum {string}
         */
        EditAction: "keep" | "cut";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RenderResponse */
        RenderResponse: {
            /** Output Path */
            output_path: string;
            /** Output Name */
            output_name: string;
        };
        /** ReviewPayload */
        ReviewPayload: {
            /**
             * Schema Version
             * @default review.v2
             */
            schema_version: string;
            video: components["schemas"]["ReviewVideoMetadata"];
            /** Segments */
            segments: components["schemas"]["ReviewTimelineSegment"][];
            /** Sentences */
            sentences: components["schemas"]["ReviewSentence"][];
        };
        /**
         * ReviewSaveRequest
         * @description Reviewer decisions expressed as the set of word indices to cut.
         */
        ReviewSaveRequest: {
            /** Cut Words */
            cut_words?: number[];
        };
        /** ReviewSaveResponse */
        ReviewSaveResponse: {
            /** Review Edl Path */
            review_edl_path: string;
            /** Keep Duration */
            keep_duration: number;
            /** Cut Duration */
            cut_duration: number;
            /** Decisions */
            decisions: number;
        };
        /** ReviewSentence */
        ReviewSentence: {
            /** Idx */
            idx: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Text */
            text: string;
            action: components["schemas"]["EditAction"];
            original_action: components["schemas"]["EditAction"];
            /** Reason */
            reason: string;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /**
             * Keep Coverage
             * @default 0
             */
            keep_coverage: number;
            /**
             * Note
             * @default
             */
            note: string;
            /**
             * Status
             * @default
             */
            status: string;
            /** Tags */
            tags?: string[];
            /**
             * Keep Confidence
             * @default 100
             */
            keep_confidence: number;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            /** Words */
            words?: components["schemas"]["ReviewWord"][];
            /** Duration */
            readonly duration: number;
        };
        /** ReviewTimelineSegment */
        ReviewTimelineSegment: {
            /** Idx */
            idx: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            action: components["schemas"]["EditAction"];
            /** Reason */
            reason: string;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /**
             * Note
             * @default
             */
            note: string;
            /** Duration */
            readonly duration: number;
        };
        /** ReviewVideoMetadata */
        ReviewVideoMetadata: {
            /** Id */
            id: string;
            /** Source Name */
            source_name: string;
            /** Source Path */
            source_path: string;
            /** Edl Path */
            edl_path: string;
            /** Review Edl Path */
            review_edl_path: string;
            /** Duration */
            duration: number;
            /** Keep Duration */
            keep_duration: number;
            /** Cut Duration */
            cut_duration: number;
            /**
             * Created At
             * @default
             */
            created_at: string;
        };
        /** ReviewVideoSummary */
        ReviewVideoSummary: {
            /** Id */
            id: string;
            /** Source Name */
            source_name: string;
            /** Source Path */
            source_path: string;
            /**
             * Has Review
             * @default false
             */
            has_review: boolean;
            /**
             * Duration
             * @default 0
             */
            duration: number;
        };
        /**
         * ReviewWord
         * @description A single transcript word with the AI decision and a keep-likelihood score.
         */
        ReviewWord: {
            /** Idx */
            idx: number;
            /** Sentence Idx */
            sentence_idx: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Text */
            text: string;
            /** Ai Kept */
            ai_kept: boolean;
            /** Kept */
            kept: boolean;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /**
             * Keep Score
             * @default 1
             */
            keep_score: number;
            /** Duration */
            readonly duration: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_videos_api_videos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewVideoSummary"][];
                };
            };
        };
    };
    get_review_api_videos__video_id__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_review_api_videos__video_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSaveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_review_api_videos__video_id__render_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    media_media__video_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
