/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Videos */
        get: operations["list_videos_api_videos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/videos/{video_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review */
        get: operations["get_review_api_videos__video_id__review_get"];
        put?: never;
        /** Save Review */
        post: operations["save_review_api_videos__video_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/videos/{video_id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Diff
         * @description Raw transcript with pipeline vs human-edit cuts overlaid for QA.
         */
        get: operations["get_diff_api_videos__video_id__diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/videos/{video_id}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render Review */
        post: operations["render_review_api_videos__video_id__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/videos/{video_id}/peaks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Peaks
         * @description Downsampled waveform peaks for the timeline (built from the cached
         *     RMS envelope; degrades to an empty waveform if no audio is available).
         */
        get: operations["get_peaks_api_videos__video_id__peaks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{video_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Media */
        get: operations["media_media__video_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CutRange
         * @description A free-form span of source video (seconds) removed from the edit.
         */
        CutRange: {
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /** DiffPayload */
        DiffPayload: {
            video: components["schemas"]["DiffVideo"];
            summary: components["schemas"]["DiffSummary"];
            /** Sentences */
            sentences?: components["schemas"]["DiffSentence"][];
        };
        /** DiffSentence */
        DiffSentence: {
            /** Idx */
            idx: number;
            /** Text */
            text: string;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Pipeline Kept */
            pipeline_kept: boolean;
            /** Human Kept */
            human_kept: boolean;
            /** Words */
            words?: components["schemas"]["DiffWord"][];
        };
        /** DiffSummary */
        DiffSummary: {
            /** Has Ground Truth */
            has_ground_truth: boolean;
            /** Raw Sentences */
            raw_sentences: number;
            /** Raw Words */
            raw_words: number;
            /** Pipeline Kept Sentences */
            pipeline_kept_sentences: number;
            /** Human Kept Sentences */
            human_kept_sentences: number;
            /** Pipeline Kept Words */
            pipeline_kept_words: number;
            /** Human Kept Words */
            human_kept_words: number;
            /** Agree Keep */
            agree_keep: number;
            /** Agree Cut */
            agree_cut: number;
            /** Pipeline Only Cut */
            pipeline_only_cut: number;
            /** Human Only Cut */
            human_only_cut: number;
        };
        /** DiffVideo */
        DiffVideo: {
            /** Id */
            id: string;
            /** Source Name */
            source_name: string;
            /** Duration */
            duration: number;
            /** Has Ground Truth */
            has_ground_truth: boolean;
        };
        /** DiffWord */
        DiffWord: {
            /** Text */
            text: string;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Pipeline Kept */
            pipeline_kept: boolean;
            /** Human Kept */
            human_kept: boolean;
        };
        /**
         * EditAction
         * @enum {string}
         */
        EditAction: "keep" | "cut";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PeaksPayload
         * @description Downsampled audio waveform for the timeline strip.
         */
        PeaksPayload: {
            /**
             * Version
             * @default peaks.v1
             */
            version: string;
            /** Duration */
            duration: number;
            /** Length */
            length: number;
            /** Peaks */
            peaks: number[];
        };
        /** RenderResponse */
        RenderResponse: {
            /** Output Path */
            output_path: string;
            /** Output Name */
            output_name: string;
        };
        /** ReviewPayload */
        ReviewPayload: {
            /**
             * Schema Version
             * @default review.v4
             */
            schema_version: string;
            video: components["schemas"]["ReviewVideoMetadata"];
            /** Segments */
            segments: components["schemas"]["ReviewTimelineSegment"][];
            /** Sentences */
            sentences: components["schemas"]["ReviewSentence"][];
            /** Cut Ranges */
            cut_ranges?: components["schemas"]["CutRange"][];
        };
        /**
         * ReviewSaveRequest
         * @description Reviewer decisions to persist.
         *
         *     The canonical form is ``cut_ranges`` (free-form source-time spans). Legacy
         *     clients may still send ``cut_words`` (word indices); it is used only when
         *     ``cut_ranges`` is omitted (``None``). An explicit empty ``cut_ranges`` list
         *     means "no cuts" (restore everything), which is distinct from omitting it.
         */
        ReviewSaveRequest: {
            /** Cut Ranges */
            cut_ranges?: components["schemas"]["CutRange"][] | null;
            /** Cut Words */
            cut_words?: number[];
        };
        /** ReviewSaveResponse */
        ReviewSaveResponse: {
            /** Review Edl Path */
            review_edl_path: string;
            /** Keep Duration */
            keep_duration: number;
            /** Cut Duration */
            cut_duration: number;
            /** Decisions */
            decisions: number;
        };
        /** ReviewSentence */
        ReviewSentence: {
            /** Idx */
            idx: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Text */
            text: string;
            action: components["schemas"]["EditAction"];
            original_action: components["schemas"]["EditAction"];
            /** Reason */
            reason: string;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /**
             * Keep Coverage
             * @default 0
             */
            keep_coverage: number;
            /**
             * Note
             * @default
             */
            note: string;
            /** Words */
            words?: components["schemas"]["ReviewWord"][];
            /** Duration */
            readonly duration: number;
        };
        /** ReviewTimelineSegment */
        ReviewTimelineSegment: {
            /** Idx */
            idx: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            action: components["schemas"]["EditAction"];
            /** Reason */
            reason: string;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /**
             * Note
             * @default
             */
            note: string;
            /** Duration */
            readonly duration: number;
        };
        /** ReviewVideoMetadata */
        ReviewVideoMetadata: {
            /** Id */
            id: string;
            /** Source Name */
            source_name: string;
            /** Source Path */
            source_path: string;
            /** Edl Path */
            edl_path: string;
            /** Review Edl Path */
            review_edl_path: string;
            /** Duration */
            duration: number;
            /** Keep Duration */
            keep_duration: number;
            /** Cut Duration */
            cut_duration: number;
            /**
             * Created At
             * @default
             */
            created_at: string;
        };
        /** ReviewVideoSummary */
        ReviewVideoSummary: {
            /** Id */
            id: string;
            /** Source Name */
            source_name: string;
            /** Source Path */
            source_path: string;
            /**
             * Has Review
             * @default false
             */
            has_review: boolean;
            /**
             * Duration
             * @default 0
             */
            duration: number;
        };
        /**
         * ReviewWord
         * @description A single transcript word with the AI decision.
         */
        ReviewWord: {
            /** Idx */
            idx: number;
            /** Sentence Idx */
            sentence_idx: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Text */
            text: string;
            /** Ai Kept */
            ai_kept: boolean;
            /** Kept */
            kept: boolean;
            /**
             * Reason
             * @default
             */
            reason: string;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /** Cut In */
            cut_in?: number | null;
            /** Cut Out */
            cut_out?: number | null;
            /** Duration */
            readonly duration: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_videos_api_videos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewVideoSummary"][];
                };
            };
        };
    };
    get_review_api_videos__video_id__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_review_api_videos__video_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSaveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_diff_api_videos__video_id__diff_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_review_api_videos__video_id__render_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_peaks_api_videos__video_id__peaks_get: {
        parameters: {
            query?: {
                buckets?: number;
            };
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeaksPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    media_media__video_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                video_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
